/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mesentllc.utilities.systemparameterutility.screens;

import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 *
 * @author 796812
 */
public class SysParamCheck extends javax.swing.JFrame {
	private final JFrame splashScr;
		
	/**
	 * Creates new form SpCheckFrame
	 */
	public SysParamCheck(JFrame splashScr) {
		initComponents();
		lblSrcUser.setVisible(false);
		txtSrcUser.setVisible(false);
		lblTgtUser.setVisible(false);
		txtTgtUser.setVisible(false);
		lblSrcPwd.setVisible(false);
		txtSrcPwd.setVisible(false);
		lblTgtPwd.setVisible(false);
		txtTgtPwd.setVisible(false);
		btnGetFile.setVisible(false);
		this.splashScr = splashScr;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTable = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        cbxSource = new javax.swing.JComboBox();
        cbxTarget = new javax.swing.JComboBox();
        lblSrcUser = new javax.swing.JLabel();
        lblTgtUser = new javax.swing.JLabel();
        txtSrcUser = new javax.swing.JTextField();
        txtTgtUser = new javax.swing.JTextField();
        lblSrcPwd = new javax.swing.JLabel();
        txtSrcPwd = new javax.swing.JPasswordField();
        txtTgtPwd = new javax.swing.JPasswordField();
        lblTgtPwd = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSP = new javax.swing.JTable();
        lblDefinition = new javax.swing.JLabel();
        chxUseFile = new javax.swing.JCheckBox();
        txtDefinition = new javax.swing.JTextField();
        btnGetFile = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("System Parameter Compare");
        setBackground(new java.awt.Color(255, 255, 255));
        setName("compareFrame"); // NOI18N
        setResizable(false);

        pnlTable.setBackground(new java.awt.Color(255, 255, 255));

        lblIcon.setBackground(new java.awt.Color(255, 255, 255));
        lblIcon.setForeground(new java.awt.Color(51, 41, 81));
        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fedex_smartpost_logo.jpg"))); // NOI18N
        lblIcon.setFocusable(false);

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(51, 41, 81));
        lblTitle.setText("System Parameter Checker");
        lblTitle.setFocusable(false);

        cbxSource.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DEV", "L2", "L3", "QAS", "PRD" }));
        cbxSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSourceActionPerformed(evt);
            }
        });

        cbxTarget.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DEV", "L2", "L3", "QAS", "PRD" }));
        cbxTarget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTargetActionPerformed(evt);
            }
        });

        lblSrcUser.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblSrcUser.setForeground(new java.awt.Color(51, 41, 81));
        lblSrcUser.setText("Username:");
        lblSrcUser.setFocusable(false);

        lblTgtUser.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblTgtUser.setForeground(new java.awt.Color(51, 41, 81));
        lblTgtUser.setText("Username:");
        lblTgtUser.setFocusable(false);

        lblSrcPwd.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblSrcPwd.setForeground(new java.awt.Color(51, 41, 81));
        lblSrcPwd.setText("Password:");
        lblSrcPwd.setFocusable(false);

        lblTgtPwd.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblTgtPwd.setForeground(new java.awt.Color(51, 41, 81));
        lblTgtPwd.setText("Password:");
        lblTgtPwd.setFocusable(false);

        tblSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Left", "Right"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSP.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tblSP);

        lblDefinition.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblDefinition.setForeground(new java.awt.Color(51, 41, 81));
        lblDefinition.setText("Parameter Category:");

        chxUseFile.setBackground(new java.awt.Color(255, 255, 255));
        chxUseFile.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        chxUseFile.setForeground(new java.awt.Color(51, 41, 81));
        chxUseFile.setText("Use Definition File");
        chxUseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxUseFileActionPerformed(evt);
            }
        });

        btnGetFile.setBackground(new java.awt.Color(153, 153, 153));
        btnGetFile.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnGetFile.setForeground(new java.awt.Color(51, 41, 81));
        btnGetFile.setText("...");
        btnGetFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetFileActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTableLayout = new javax.swing.GroupLayout(pnlTable);
        pnlTable.setLayout(pnlTableLayout);
        pnlTableLayout.setHorizontalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTableLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlTableLayout.createSequentialGroup()
                        .addGroup(pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTableLayout.createSequentialGroup()
                                .addComponent(lblIcon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTitle))
                            .addComponent(chxUseFile)
                            .addGroup(pnlTableLayout.createSequentialGroup()
                                .addGroup(pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlTableLayout.createSequentialGroup()
                                        .addGroup(pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblSrcUser)
                                            .addComponent(lblSrcPwd))
                                        .addGap(4, 4, 4)
                                        .addGroup(pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtSrcUser)
                                            .addComponent(txtSrcPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(cbxSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(84, 84, 84)
                                .addGroup(pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTgtPwd)
                                    .addComponent(cbxTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTgtUser))
                                .addGap(4, 4, 4)
                                .addGroup(pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTgtUser)
                                    .addComponent(txtTgtPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlTableLayout.createSequentialGroup()
                                .addComponent(lblDefinition)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDefinition, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGetFile, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlTableLayout.setVerticalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(lblIcon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chxUseFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDefinition)
                    .addComponent(txtDefinition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGetFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSrcUser)
                    .addComponent(lblTgtUser)
                    .addComponent(txtSrcUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTgtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSrcPwd)
                    .addComponent(txtSrcPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTgtPwd)
                    .addComponent(txtTgtPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSourceActionPerformed
        if (((String)cbxSource.getSelectedItem()).equals("PRD")) {
			lblSrcUser.setVisible(true);
			txtSrcUser.setVisible(true);
			lblSrcPwd.setVisible(true);
			txtSrcPwd.setVisible(true);
		}
		else {
			lblSrcUser.setVisible(false);
			txtSrcUser.setVisible(false);
			lblSrcPwd.setVisible(false);
			txtSrcPwd.setVisible(false);
		}
    }//GEN-LAST:event_cbxSourceActionPerformed

    private void cbxTargetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTargetActionPerformed
        if (((String)cbxTarget.getSelectedItem()).equals("PRD")) {
			lblTgtUser.setVisible(true);
			txtTgtUser.setVisible(true);
			lblTgtPwd.setVisible(true);
			txtTgtPwd.setVisible(true);
		}
		else {
			lblTgtUser.setVisible(false);
			txtTgtUser.setVisible(false);
			lblTgtPwd.setVisible(false);
			txtTgtPwd.setVisible(false);
		}
    }//GEN-LAST:event_cbxTargetActionPerformed

    private void btnGetFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetFileActionPerformed
		JFileChooser fileChooser = new JFileChooser();
		
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            txtDefinition.setText(fileChooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_btnGetFileActionPerformed

    private void chxUseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxUseFileActionPerformed
        if (chxUseFile.isSelected()) {
			lblDefinition.setText("Parameter Definition File:");
			txtDefinition.setText("");
			btnGetFile.setVisible(true);
		}
		else {
			lblDefinition.setText("Parameter Category:");
			txtDefinition.setText("");
			btnGetFile.setVisible(false);
		}
    }//GEN-LAST:event_chxUseFileActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
		this.setVisible(false);
		splashScr.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGetFile;
    private javax.swing.JComboBox cbxSource;
    private javax.swing.JComboBox cbxTarget;
    private javax.swing.JCheckBox chxUseFile;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDefinition;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblSrcPwd;
    private javax.swing.JLabel lblSrcUser;
    private javax.swing.JLabel lblTgtPwd;
    private javax.swing.JLabel lblTgtUser;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JTable tblSP;
    private javax.swing.JTextField txtDefinition;
    private javax.swing.JPasswordField txtSrcPwd;
    private javax.swing.JTextField txtSrcUser;
    private javax.swing.JPasswordField txtTgtPwd;
    private javax.swing.JTextField txtTgtUser;
    // End of variables declaration//GEN-END:variables
}
