package com.mesentllc.utilities.systemparameterutility.screens;

import com.mesentllc.utilities.systemparameterutility.FileUtility;
import com.mesentllc.utilities.systemparameterutility.SystemParameterUtilities;
import com.mesentllc.utilities.systemparameterutility.enums.PFEnvironment;
import com.mesentllc.utilities.systemparameterutility.enums.PFSystem;
import com.mesentllc.utilities.systemparameterutility.exceptions.FileProcessingException;
import com.mesentllc.utilities.systemparameterutility.exceptions.SystemParameterException;
import com.mesentllc.utilities.systemparameterutility.model.Instance;
import com.mesentllc.utilities.systemparameterutility.types.SystemParameter;
import com.mesentllc.utilities.systemparameterutility.types.SystemParameters;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class SysParamInstall extends JFrame {
   	private final String[][] sUser = new String[2][5];
	private final String[][] sPwd = new String[2][5];
    private final JFrame splashScr;
	private final FileUtility fileUtility;
	
    /**
     * Creates new form SystemParamInstall
     * @param splashScr
     */
    public SysParamInstall(JFrame splashScr) {
        loadAuthorization();
        initComponents();
		fileUtility = new FileUtility();
        cbxSystem.setSelectedIndex(1);
        this.splashScr = splashScr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblFile = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        cbxSystem = new javax.swing.JComboBox();
        lblSystem = new javax.swing.JLabel();
        lblEnvironment = new javax.swing.JLabel();
        cbxEnvironment = new javax.swing.JComboBox();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtFilename = new javax.swing.JTextField();
        btnFileChooser = new javax.swing.JButton();
        btnInstall = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("System Parameter File Install");

        lblFile.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFile.setText("File:");

        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUsername.setText("Username:");

        cbxSystem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EVS", "RODeS" }));
        cbxSystem.setSelectedItem("RODeS");
        cbxSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSystemActionPerformed(evt);
            }
        });

        lblSystem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSystem.setText("System:");

        lblEnvironment.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEnvironment.setText("Environment:");

        cbxEnvironment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "L0", "L2", "L3", "L4", "PRD" }));
        cbxEnvironment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEnvironmentActionPerformed(evt);
            }
        });

        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsernameFocusLost(evt);
            }
        });

        lblPassword.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPassword.setText("Password:");

        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });

        btnFileChooser.setText("...");
        btnFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileChooserActionPerformed(evt);
            }
        });

        btnInstall.setText("Install File");
        btnInstall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstallActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFilename)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInstall))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUsername)
                        .addGap(12, 12, 12)
                        .addComponent(lblPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSystem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxSystem, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(lblEnvironment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxEnvironment, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxSystem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSystem))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxEnvironment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblEnvironment)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFile)
                    .addComponent(txtFilename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFileChooser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInstall)
                    .addComponent(btnBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusLost
        sUser[cbxSystem.getSelectedIndex()][cbxEnvironment.getSelectedIndex()] = txtUsername.getText().trim();
    }//GEN-LAST:event_txtUsernameFocusLost

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        sPwd[cbxSystem.getSelectedIndex()][cbxEnvironment.getSelectedIndex()] = new String(txtPassword.getPassword()).trim();
    }//GEN-LAST:event_txtPasswordFocusLost

    private void cbxEnvironmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEnvironmentActionPerformed
        txtUsername.setText(sUser[cbxSystem.getSelectedIndex()][cbxEnvironment.getSelectedIndex()]);
        txtPassword.setText(sPwd[cbxSystem.getSelectedIndex()][cbxEnvironment.getSelectedIndex()]);
    }//GEN-LAST:event_cbxEnvironmentActionPerformed

    private void cbxSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSystemActionPerformed
        txtUsername.setText(sUser[cbxSystem.getSelectedIndex()][cbxEnvironment.getSelectedIndex()]);
        txtPassword.setText(sPwd[cbxSystem.getSelectedIndex()][cbxEnvironment.getSelectedIndex()]);
    }//GEN-LAST:event_cbxSystemActionPerformed

    private void btnInstallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstallActionPerformed
		Instance instance = new Instance();
		String filename = txtFilename.getText().trim();
		
		if (filename.length() == 0) {
            JOptionPane.showMessageDialog(this, "You need to supply a file to install.");
            return;
        }
		instance.setPfEnvironment(PFEnvironment.valueOf((String)cbxEnvironment.getSelectedItem()));
		instance.setPfSystem(PFSystem.valueOf((String)cbxSystem.getSelectedItem()));
        instance.setUsername(txtUsername.getText().trim());
        instance.setPassword(new String(txtPassword.getPassword()).trim());
        if (instance.getUsername().length() == 0 || instance.getPassword().length() == 0) {
            JOptionPane.showMessageDialog(this, "Username/Password can't be empty.");
            return;
        }
		try {
			SystemParameters systemParameters = fileUtility.xmlFileToParameters(filename);
			if (systemParameters == null) {
				if (!fileUtility.processFlatFile(instance, filename)) {
					JOptionPane.showMessageDialog(this, "Invalid file contents - Not XML or proper format.");
				}
			}
			else {
				List<SystemParameter> spList = systemParameters.getSystemParameter();
				for (SystemParameter systemParameter : spList) {
					if ((systemParameter.getLongValue() != null) && (systemParameter.getLongValue().length() > 0)){
						systemParameter.setValue(systemParameter.getLongValue());
					}
					SystemParameterUtilities.processSystemParameter(instance, systemParameter);
				}
			}
		}
		catch (FileProcessingException fpe) {
			JOptionPane.showMessageDialog(this, fpe);
		}
		catch (SystemParameterException fpe) {
			JOptionPane.showMessageDialog(this, fpe);
		}
    }//GEN-LAST:event_btnInstallActionPerformed

    private void btnFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileChooserActionPerformed
        JFileChooser chooser = new JFileChooser();
        
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            txtFilename.setText(chooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_btnFileChooserActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
        splashScr.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

	private void loadAuthorization() {
        for (int outer = 0; outer < 2; outer++) {
            for (int inner = 0; inner < 5; inner++) {
                sUser[outer][inner] = SystemParameterUtilities.ORACLE_USER[outer][inner];
                sPwd[outer][inner] = SystemParameterUtilities.ORACLE_PWD[outer][inner];
            }
        }
    }
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFileChooser;
    private javax.swing.JButton btnInstall;
    private javax.swing.JComboBox cbxEnvironment;
    private javax.swing.JComboBox cbxSystem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEnvironment;
    private javax.swing.JLabel lblFile;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSystem;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtFilename;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
